services:
  # 主应用服务 - 后端API（开发版本）
  app:
    build:
      context: .
      dockerfile: Dockerfile.fast
    container_name: video-converter-app-dev
    restart: unless-stopped
    environment:
      - GIN_MODE=debug
      - TZ=Asia/Shanghai
    ports:
      - "9002:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml  # 使用本地配置
    networks:
      - video-converter-net

  # Nginx反向代理 - 前端
  nginx:
    image: nginx:alpine
    container_name: video-converter-nginx-dev
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "9001:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - video-converter-net

networks:
  video-converter-net:
    driver: bridge 
